from .ideogram_studio import (
    NODE_CLASS_MAPPINGS as _STUDIO_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _STUDIO_NAMES,
)
from .overrides import (
    NODE_CLASS_MAPPINGS as _OVERRIDE_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _OVERRIDE_NAMES,
)
from .refsync import (
    NODE_CLASS_MAPPINGS as _REFSYNC_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _REFSYNC_NAMES,
)

NODE_CLASS_MAPPINGS = {**_STUDIO_CLASSES, **_OVERRIDE_CLASSES, **_REFSYNC_CLASSES}
NODE_DISPLAY_NAME_MAPPINGS = {**_STUDIO_NAMES, **_OVERRIDE_NAMES, **_REFSYNC_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
